# Generated by Django 4.1.3 on 2022-12-07 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeature',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acousticness', models.FloatField(blank=True, default=None, null=True)),
                ('danceability', models.FloatField(blank=True, default=None, null=True)),
                ('energy', models.FloatField(blank=True, default=None, null=True)),
                ('instrumentalness', models.FloatField(blank=True, default=None, null=True)),
                ('liveness', models.FloatField(blank=True, default=None, null=True)),
                ('speechiness', models.FloatField(blank=True, default=None, null=True)),
                ('loudness', models.FloatField(blank=True, default=None, null=True)),
                ('valence', models.FloatField(blank=True, default=None, null=True)),
                ('tempo', models.FloatField(blank=True, default=None, null=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
