# Generated by Django 4.1.3 on 2022-12-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_audiofeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='songs.artist'),
        ),
    ]
